=== nhsneto/ldd/revisao2/Copa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="copa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fase" type="Fase" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="ano" type="xs:gYear" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Fase">
        <xs:sequence>
            <xs:element name="grupo" type="Grupo" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="tipo">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="grupos|finais" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Grupo">
        <xs:sequence>
            <xs:element name="jogo" type="Jogo" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="nome" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Jogo">
        <xs:choice>
            <xs:element name="eventos" type="Eventos" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="data" type="xs:dateTime" />
        <xs:attribute name="mandante" type="xs:string" />
        <xs:attribute name="visitante" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="Eventos">
        <xs:sequence>
            <xs:element name="evento" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="jogador" type="xs:string"/>
                        <xs:element name="minuto" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="tipo" type="xs:string" />
                    <xs:attribute name="time" type="xs:string" />
                    <xs:attribute name="type">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="contra|penalti" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== nhsneto/ldd/revisao2/Copa2018.xml
<?xml version="1.0" encoding="UTF-8"?>
<copa ano="2018" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Copa.xsd">
    <fase tipo="grupos">
        <grupo nome="A">
            <jogo data="2018-06-14T18:00:00+03:00" mandante="Rússia" visitante="Arábia Saudita">
                <eventos>
                    <evento tipo="gol" time="mandante">
                        <jogador>Gazinsky</jogador>
                        <minuto>12</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Cheryshev</jogador>
                        <minuto>43</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Dzyuba</jogador>
                        <minuto>71</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Cheryshev</jogador>
                        <minuto>90+1</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Golovin</jogador>
                        <minuto>90+4</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-15T17:00:00+05:00" mandante="Egito" visitante="Uruguai">
                <eventos>
                    <evento tipo="gol" time="visitante">
                        <jogador>Giménez</jogador>
                        <minuto>89</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-19T21:00:00+03:00" mandante="Rússia" visitante="Egito">
                <eventos>
                    <evento tipo="gol" time="visitante" type="contra">
                        <jogador>Fathy</jogador>
                        <minuto>47</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Cheryshev</jogador>
                        <minuto>59</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Dzyuba</jogador>
                        <minuto>62</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante" type="penalti">
                        <jogador>Salah</jogador>
                        <minuto>73</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-20T18:00:00+03:00" mandante="Uruguai" visitante="Arábia Saudita">
                <eventos>
                    <evento tipo="gol" time="mandante">
                        <jogador>Suárez</jogador>
                        <minuto>23</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-25T18:00:00+04:00" mandante="Uruguai" visitante="Rússia">
                <eventos>
                    <evento tipo="gol" time="mandante">
                        <jogador>Suárez</jogador>
                        <minuto>10</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante" type="contra">
                        <jogador>Cheryshev</jogador>
                        <minuto>23</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Cavani</jogador>
                        <minuto>90</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-25T17:00:00+03:00" mandante="Arábia Saudita" visitante="Egito">
                <eventos>
                    <evento tipo="gol" time="mandante" type="penalti">
                        <jogador>Al-Faraj</jogador>
                        <minuto>45+6</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante">
                        <jogador>Salah</jogador>
                        <minuto>22</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Al-Dawsari</jogador>
                        <minuto>90+5</minuto>
                    </evento>
                </eventos>
            </jogo>
        </grupo>
        <grupo nome="B">
            <jogo data="2018-06-15T18:00:00+02:00" mandante="Marrocos" visitante="Irã">
                <eventos>
                    <evento tipo="gol" time="mandante" type="contra">
                        <jogador>Bouhaddouz</jogador>
                        <minuto>90+5</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-15T21:00:00+03:00" mandante="Portugal" visitante="Espanha">
                <eventos>
                    <evento tipo="gol" time="mandante" type="penalti">
                        <jogador>Cristiano Ronaldo</jogador>
                        <minuto>4</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Cristiano Ronaldo</jogador>
                        <minuto>44</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Cristiano Ronaldo</jogador>
                        <minuto>88</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante">
                        <jogador>Diego Costa</jogador>
                        <minuto>24</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante">
                        <jogador>Diego Costa</jogador>
                        <minuto>55</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante">
                        <jogador>Nacho</jogador>
                        <minuto>58</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-20T15:00:00+03:00" mandante="Portugal" visitante="Marrocos">
                <eventos>
                    <evento tipo="gol" time="mandante" type="penalti">
                        <jogador>Cristiano Ronaldo</jogador>
                        <minuto>4</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-20T21:00:00+03:00" mandante="Irã" visitante="Espanha">
                <eventos>
                    <evento tipo="gol" time="visitante">
                        <jogador>Diego Costa</jogador>
                        <minuto>54</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-25T21:00:00+03:00" mandante="Irã" visitante="Portugal">
                <eventos>
                    <evento tipo="gol" time="visitante">
                        <jogador>Quaresma</jogador>
                        <minuto>45</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante" type="penalti">
                        <jogador>Ansarifard</jogador>
                        <minuto>90+3</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-25T20:00:00+02:00" mandante="Espanha" visitante="Marrocos">
                <eventos>
                    <evento tipo="gol" time="visitante">
                        <jogador>En-Nesyri</jogador>
                        <minuto>81</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante">
                        <jogador>Boutaïb</jogador>
                        <minuto>14</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Isco</jogador>
                        <minuto>19</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Aspas</jogador>
                        <minuto>90+1</minuto>
                    </evento>
                </eventos>
            </jogo>
        </grupo>
        <grupo nome="C">
            <jogo data="2018-06-16T13:00:00+03:00" mandante="França" visitante="Austrália">
                <eventos>
                    <evento tipo="gol" time="visitante" type="contra">
                        <jogador>Behich</jogador>
                        <minuto>81</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante" type="penalti">
                        <jogador>Griezmann</jogador>
                        <minuto>58</minuto>
                    </evento>
                    <evento tipo="gol" time="visitante" type="penalti">
                        <jogador>Jedinak</jogador>
                        <minuto>62</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-16T19:00:00+03:00" mandante="Peru" visitante="Dinamarca">
                <eventos>
                    <evento tipo="gol" time="visitante">
                        <jogador>Poulsen</jogador>
                        <minuto>59</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-21T16:00:00+04:00" mandante="Dinamarca" visitante="Austrália">
                <eventos>
                    <evento tipo="gol" time="visitante" type="penalti">
                        <jogador>Jedinak</jogador>
                        <minuto>38</minuto>
                    </evento>
                    <evento tipo="gol" time="mandante">
                        <jogador>Eriksen</jogador>
                        <minuto>7</minuto>
                    </evento>
                </eventos>
            </jogo>
            <jogo data="2018-06-21T20:00:00+05:00" mandante="França" visitante="Peru">
